name: Lint PHP
on:
  pull_request:
    branches: master
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: PHPLint
        uses: overtrue/phplint@master
        with:
          path: .
          options: --exclude=*.log
