name: Lint PHP
on:
  push:
    branches: actions
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: PHPLint
        uses: overtrue/phplint@master
        with:
          path: .
          options: --exclude=*.log
